name: Python Calculator Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Create empty requirements.txt if it doesn't exist
        if [ ! -f "requirements.txt" ]; then
          touch requirements.txt
        fi
        pip install -r requirements.txt
    
    - name: Verify Python version
      run: python --version
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        cd tests
        python -m unittest test.py